projects:
  - id: 414480
    sources:
      - dir: "%crowdin_download_path%"
        crowdinPath:
          dir: "/lang"
          filename: "en_us.json"
        exportPattern:
          dir: "/lang"
          filename: "%locale_with_underscore%.json"
        includes:
          - pattern: "en_us.json"